### ISSUE TITLE
Create config file

### ISSUE THREAD

**Issue by jsz7** [cyedge/CryptoTeleBot#2]
Right now it seems like it's useless, because there will be just `TOKEN` stored there. But later it can contains things like `LOG_FILE=...`, `DEV_MODE=Y`, `TIMEZONE=...` etc.

I thing python has some library for parsing `.ini` files, so we should probably use it.

Also we can have 2 config files one for development environment, second for production. At first, app will try load dev config and if it's missing it will load production config.

Also there is missing `requirements.txt` file

**Comment by lukasbalazik123** [comment]
Commit #5
